import json
from datetime import datetime, timedelta
from sqlalchemy.orm import Session
from backend import models

def seed_geographic_hierarchy(db: Session):
    """Populates Country, States, and Districts for scalable geographic coverage."""
    # 1. Country: India (with hooks for international expansion)
    country = models.Country(
        id="india",
        name="India",
        code="IN",
        center_lat=21.7679,
        center_lng=78.8718,
        zoom=5,
        description="National Hydrological & Disaster Early-Warning Network under NDMA, CWC, and IMD guidelines."
    )
    db.add(country)

    # 2. States across India
    states = [
        models.State(
            id="tamil_nadu",
            country_id="india",
            name="Tamil Nadu",
            code="TN",
            center_lat=11.1271,
            center_lng=78.6569,
            zoom=7,
            active_risk_level="critical",
            monsoon_status="Northeast Monsoon Active (Red Alert)",
            total_stations=22,
            description="Vulnerable coastal plain with multiple river basins (Adyar, Cooum, Palar, Cauvery, Vaigai) and dense urban stormwater networks."
        ),
        models.State(
            id="maharashtra",
            country_id="india",
            name="Maharashtra",
            code="MH",
            center_lat=19.7515,
            center_lng=75.7139,
            zoom=7,
            active_risk_level="high",
            monsoon_status="Southwest Monsoon Coastal Surge",
            total_stations=6,
            description="Konkan coastal belt prone to simultaneous high astronomical tides and Western Ghats torrential rainfall."
        ),
        models.State(
            id="karnataka",
            country_id="india",
            name="Karnataka",
            code="KA",
            center_lat=15.3173,
            center_lng=75.7139,
            zoom=7,
            active_risk_level="moderate",
            monsoon_status="Scattered Intense Cloudbursts",
            total_stations=5,
            description="Deccan plateau highland with interconnected urban lake cascades and coastal river valleys."
        ),
        models.State(
            id="kerala",
            country_id="india",
            name="Kerala",
            code="KL",
            center_lat=10.8505,
            center_lng=76.2711,
            zoom=8,
            active_risk_level="critical",
            monsoon_status="Extremely Heavy Rainfall (Red Alert)",
            total_stations=4,
            description="Steep Western Ghats catchment draining rapidly into backwaters and low-lying coastal plains."
        ),
        models.State(
            id="assam",
            country_id="india",
            name="Assam",
            code="AS",
            center_lat=26.2006,
            center_lng=92.9376,
            zoom=7,
            active_risk_level="critical",
            monsoon_status="Brahmaputra Above Danger Level",
            total_stations=4,
            description="Alluvial Brahmaputra and Barak river basins subject to Himalayan flood waves and bank erosion."
        ),
        models.State(
            id="telangana",
            country_id="india",
            name="Telangana",
            code="TG",
            center_lat=18.1124,
            center_lng=79.0193,
            zoom=7,
            active_risk_level="moderate",
            monsoon_status="Localized Convective Storms",
            total_stations=3,
            description="Semi-arid plateau drained by Godavari and Krishna tributaries, prone to urban flash flooding."
        ),
        models.State(
            id="west_bengal",
            country_id="india",
            name="West Bengal",
            code="WB",
            center_lat=22.9868,
            center_lng=87.8550,
            zoom=7,
            active_risk_level="moderate",
            monsoon_status="Bay of Bengal Low Pressure",
            total_stations=2,
            description="Lower Gangetic plain and coastal Sundarbans delta vulnerable to tidal storm surges."
        ),
        models.State(
            id="odisha",
            country_id="india",
            name="Odisha",
            code="OD",
            center_lat=20.9517,
            center_lng=85.0985,
            zoom=7,
            active_risk_level="moderate",
            monsoon_status="Coastal Squall Warning",
            total_stations=2,
            description="Mahanadi delta basin prone to cyclone-induced coastal floods and river breaches."
        ),
        models.State(
            id="gujarat",
            country_id="india",
            name="Gujarat",
            code="GJ",
            center_lat=22.2587,
            center_lng=71.1924,
            zoom=7,
            active_risk_level="low",
            monsoon_status="Normal Catchment Flow",
            total_stations=2,
            description="West-flowing river systems (Narmada, Tapi, Sabarmati) regulated by major dams."
        )
    ]
    db.add_all(states)

    # 3. Districts
    districts = [
        # Tamil Nadu Districts
        models.District(id="dist-chennai", state_id="tamil_nadu", name="Chennai", center_lat=13.0827, center_lng=80.2707, zoom=12, active_risk_level="critical", rainfall_mm=72.4, headquarters="Ripon Building"),
        models.District(id="dist-tiruvallur", state_id="tamil_nadu", name="Tiruvallur", center_lat=13.1432, center_lng=79.9074, zoom=11, active_risk_level="high", rainfall_mm=64.0, headquarters="Tiruvallur"),
        models.District(id="dist-chengalpattu", state_id="tamil_nadu", name="Chengalpattu", center_lat=12.6922, center_lng=79.9766, zoom=11, active_risk_level="high", rainfall_mm=58.5, headquarters="Chengalpattu"),
        models.District(id="dist-cuddalore", state_id="tamil_nadu", name="Cuddalore", center_lat=11.7480, center_lng=79.7714, zoom=11, active_risk_level="critical", rainfall_mm=88.2, headquarters="Cuddalore"),
        models.District(id="dist-madurai", state_id="tamil_nadu", name="Madurai", center_lat=9.9252, center_lng=78.1198, zoom=11, active_risk_level="moderate", rainfall_mm=36.0, headquarters="Madurai"),
        models.District(id="dist-coimbatore", state_id="tamil_nadu", name="Coimbatore", center_lat=11.0168, center_lng=76.9558, zoom=11, active_risk_level="low", rainfall_mm=18.0, headquarters="Coimbatore"),
        # Maharashtra Districts
        models.District(id="dist-mumbai-urban", state_id="maharashtra", name="Mumbai Urban", center_lat=18.9388, center_lng=72.8354, zoom=12, active_risk_level="critical", rainfall_mm=52.0, headquarters="Mumbai"),
        models.District(id="dist-mumbai-suburban", state_id="maharashtra", name="Mumbai Suburban", center_lat=19.1136, center_lng=72.8697, zoom=12, active_risk_level="high", rainfall_mm=44.0, headquarters="Bandra"),
        models.District(id="dist-thane", state_id="maharashtra", name="Thane", center_lat=19.2183, center_lng=72.9781, zoom=11, active_risk_level="moderate", rainfall_mm=38.0, headquarters="Thane"),
        models.District(id="dist-pune", state_id="maharashtra", name="Pune", center_lat=18.5204, center_lng=73.8567, zoom=11, active_risk_level="low", rainfall_mm=22.0, headquarters="Pune"),
        # Karnataka Districts
        models.District(id="dist-bengaluru-urban", state_id="karnataka", name="Bengaluru Urban", center_lat=12.9716, center_lng=77.5946, zoom=12, active_risk_level="moderate", rainfall_mm=22.0, headquarters="Bengaluru"),
        models.District(id="dist-dakshina-kannada", state_id="karnataka", name="Dakshina Kannada", center_lat=12.8703, center_lng=74.8806, zoom=11, active_risk_level="high", rainfall_mm=62.0, headquarters="Mangaluru"),
        # Kerala Districts
        models.District(id="dist-ernakulam", state_id="kerala", name="Ernakulam", center_lat=9.9816, center_lng=76.2999, zoom=12, active_risk_level="critical", rainfall_mm=94.0, headquarters="Kochi"),
        models.District(id="dist-wayanad", state_id="kerala", name="Wayanad", center_lat=11.6854, center_lng=76.1320, zoom=11, active_risk_level="high", rainfall_mm=81.0, headquarters="Kalpetta"),
        # Assam Districts
        models.District(id="dist-kamrup-metro", state_id="assam", name="Kamrup Metropolitan", center_lat=26.1445, center_lng=91.7362, zoom=12, active_risk_level="critical", rainfall_mm=76.0, headquarters="Guwahati"),
        # Telangana Districts
        models.District(id="dist-hyderabad", state_id="telangana", name="Hyderabad", center_lat=17.3850, center_lng=78.4867, zoom=12, active_risk_level="moderate", rainfall_mm=19.0, headquarters="Hyderabad")
    ]
    db.add_all(districts)
    db.commit()


def seed_monitoring_stations(db: Session):
    """Populates 40+ realistic, richly-attributed monitoring stations across India."""
    now = datetime.utcnow()
    
    stations = [
        # =========================================================================
        # TAMIL NADU - CHENNAI & SURROUNDING DISTRICTS (22 STATIONS)
        # =========================================================================
        models.MonitoringStation(
            id="STN-TN-CHE-001",
            name="Adyar River - Saidapet Bridge Gauge",
            station_type="river_gauge",
            country_id="india",
            state_id="tamil_nadu",
            district_id="dist-chennai",
            city_id="chennai",
            zone_id="fz-1",
            latitude=13.0185,
            longitude=80.2223,
            water_level=2.85,
            warning_level=2.20,
            danger_level=2.90,
            flow_rate=420.0,
            rainfall=74.0,
            drainage_capacity=45.0,
            risk_level="CRITICAL",
            confidence=97.0,
            sensor_status="ALERT",
            data_source="DEMO/SIMULATED",
            battery_level=94.0,
            trend="rising",
            last_updated=now - timedelta(minutes=2)
        ),
        models.MonitoringStation(
            id="STN-TN-CHE-002",
            name="Adyar River - Kotturpuram Sluice",
            station_type="river_gauge",
            country_id="india",
            state_id="tamil_nadu",
            district_id="dist-chennai",
            city_id="chennai",
            zone_id="fz-1",
            latitude=13.0232,
            longitude=80.2410,
            water_level=2.60,
            warning_level=2.00,
            danger_level=2.80,
            flow_rate=380.0,
            rainfall=71.0,
            drainage_capacity=48.0,
            risk_level="HIGH",
            confidence=96.0,
            sensor_status="ALERT",
            data_source="DEMO/SIMULATED",
            battery_level=98.0,
            trend="rising",
            last_updated=now - timedelta(minutes=3)
        ),
        models.MonitoringStation(
            id="STN-TN-CHE-003",
            name="Chembarambakkam Outflow Regulator",
            station_type="reservoir_spillway",
            country_id="india",
            state_id="tamil_nadu",
            district_id="dist-chengalpattu",
            city_id="chennai",
            latitude=13.0118,
            longitude=80.0573,
            water_level=4.10,
            warning_level=3.80,
            danger_level=4.50,
            flow_rate=650.0,
            rainfall=82.0,
            drainage_capacity=52.0,
            risk_level="CRITICAL",
            confidence=99.0,
            sensor_status="ALERT",
            data_source="DEMO/SIMULATED",
            battery_level=100.0,
            trend="rising",
            last_updated=now - timedelta(minutes=1)
        ),
        models.MonitoringStation(
            id="STN-TN-CHE-004",
            name="Velachery MRTS Storm Culvert",
            station_type="urban_storm_drain",
            country_id="india",
            state_id="tamil_nadu",
            district_id="dist-chennai",
            city_id="chennai",
            zone_id="fz-1",
            latitude=12.9792,
            longitude=80.2185,
            water_level=1.45,
            warning_level=0.90,
            danger_level=1.20,
            flow_rate=42.0,
            rainfall=68.0,
            drainage_capacity=32.0,
            risk_level="CRITICAL",
            confidence=95.0,
            sensor_status="ALERT",
            data_source="DEMO/SIMULATED",
            battery_level=91.0,
            trend="rising",
            last_updated=now - timedelta(minutes=4)
        ),
        models.MonitoringStation(
            id="STN-TN-CHE-005",
            name="Velachery Lake Surplus Spillway",
            station_type="reservoir_spillway",
            country_id="india",
            state_id="tamil_nadu",
            district_id="dist-chennai",
            city_id="chennai",
            zone_id="fz-1",
            latitude=12.9830,
            longitude=80.2150,
            water_level=1.80,
            warning_level=1.40,
            danger_level=2.00,
            flow_rate=78.0,
            rainfall=66.0,
            drainage_capacity=40.0,
            risk_level="HIGH",
            confidence=96.0,
            sensor_status="ALERT",
            data_source="DEMO/SIMULATED",
            battery_level=95.0,
            trend="rising",
            last_updated=now - timedelta(minutes=5)
        ),
        models.MonitoringStation(
            id="STN-TN-CHE-006",
            name="Buckingham Canal - Mylapore Lock",
            station_type="coastal_tide_station",
            country_id="india",
            state_id="tamil_nadu",
            district_id="dist-chennai",
            city_id="chennai",
            latitude=13.0382,
            longitude=80.2678,
            water_level=1.95,
            warning_level=1.60,
            danger_level=2.20,
            flow_rate=85.0,
            rainfall=58.0,
            drainage_capacity=54.0,
            risk_level="HIGH",
            confidence=94.0,
            sensor_status="ALERT",
            data_source="DEMO/SIMULATED",
            battery_level=96.0,
            trend="rising",
            last_updated=now - timedelta(minutes=6)
        ),
        models.MonitoringStation(
            id="STN-TN-CHE-007",
            name="Buckingham Canal - Sholinganallur Weir",
            station_type="urban_storm_drain",
            country_id="india",
            state_id="tamil_nadu",
            district_id="dist-chennai",
            city_id="chennai",
            latitude=12.9010,
            longitude=80.2280,
            water_level=1.60,
            warning_level=1.80,
            danger_level=2.20,
            flow_rate=62.0,
            rainfall=52.0,
            drainage_capacity=60.0,
            risk_level="MODERATE",
            confidence=93.0,
            sensor_status="ONLINE",
            data_source="DEMO/SIMULATED",
            battery_level=97.0,
            trend="steady",
            last_updated=now - timedelta(minutes=8)
        ),
        models.MonitoringStation(
            id="STN-TN-CHE-008",
            name="Cooum River - Chintadripet Gauge",
            station_type="river_gauge",
            country_id="india",
            state_id="tamil_nadu",
            district_id="dist-chennai",
            city_id="chennai",
            latitude=13.0780,
            longitude=80.2710,
            water_level=2.10,
            warning_level=1.80,
            danger_level=2.50,
            flow_rate=140.0,
            rainfall=64.0,
            drainage_capacity=50.0,
            risk_level="HIGH",
            confidence=96.0,
            sensor_status="ALERT",
            data_source="DEMO/SIMULATED",
            battery_level=93.0,
            trend="rising",
            last_updated=now - timedelta(minutes=3)
        ),
        models.MonitoringStation(
            id="STN-TN-CHE-009",
            name="Cooum River - Maduravoyal Sluice",
            station_type="river_gauge",
            country_id="india",
            state_id="tamil_nadu",
            district_id="dist-chennai",
            city_id="chennai",
            latitude=13.0650,
            longitude=80.1650,
            water_level=1.85,
            warning_level=1.90,
            danger_level=2.40,
            flow_rate=115.0,
            rainfall=62.0,
            drainage_capacity=56.0,
            risk_level="MODERATE",
            confidence=95.0,
            sensor_status="ONLINE",
            data_source="DEMO/SIMULATED",
            battery_level=99.0,
            trend="steady",
            last_updated=now - timedelta(minutes=7)
        ),
        models.MonitoringStation(
            id="STN-TN-CHE-010",
            name="Madipakkam Lake Discharge Node",
            station_type="culvert_sensor",
            country_id="india",
            state_id="tamil_nadu",
            district_id="dist-chennai",
            city_id="chennai",
            zone_id="fz-2",
            latitude=12.9620,
            longitude=80.1980,
            water_level=1.25,
            warning_level=0.85,
            danger_level=1.10,
            flow_rate=36.0,
            rainfall=69.0,
            drainage_capacity=38.0,
            risk_level="CRITICAL",
            confidence=97.0,
            sensor_status="ALERT",
            data_source="DEMO/SIMULATED",
            battery_level=90.0,
            trend="rising",
            last_updated=now - timedelta(minutes=2)
        ),
        models.MonitoringStation(
            id="STN-TN-CHE-011",
            name="Mudichur Lowlands Culvert #4",
            station_type="culvert_sensor",
            country_id="india",
            state_id="tamil_nadu",
            district_id="dist-chengalpattu",
            city_id="chennai",
            zone_id="fz-3",
            latitude=12.9210,
            longitude=80.0680,
            water_level=1.65,
            warning_level=1.00,
            danger_level=1.30,
            flow_rate=58.0,
            rainfall=76.0,
            drainage_capacity=35.0,
            risk_level="CRITICAL",
            confidence=98.0,
            sensor_status="ALERT",
            data_source="DEMO/SIMULATED",
            battery_level=92.0,
            trend="rising",
            last_updated=now - timedelta(minutes=1)
        ),
        models.MonitoringStation(
            id="STN-TN-CHE-012",
            name="Tambaram GST Road Underpass Sump",
            station_type="urban_storm_drain",
            country_id="india",
            state_id="tamil_nadu",
            district_id="dist-chengalpattu",
            city_id="chennai",
            latitude=12.9249,
            longitude=80.1000,
            water_level=1.10,
            warning_level=0.80,
            danger_level=1.20,
            flow_rate=24.0,
            rainfall=64.0,
            drainage_capacity=58.0,
            risk_level="HIGH",
            confidence=94.0,
            sensor_status="ALERT",
            data_source="DEMO/SIMULATED",
            battery_level=95.0,
            trend="steady",
            last_updated=now - timedelta(minutes=5)
        ),
        models.MonitoringStation(
            id="STN-TN-CHE-013",
            name="Porur Lake Surplus Channel",
            station_type="reservoir_spillway",
            country_id="india",
            state_id="tamil_nadu",
            district_id="dist-chennai",
            city_id="chennai",
            latitude=13.0360,
            longitude=80.1580,
            water_level=1.40,
            warning_level=1.50,
            danger_level=2.00,
            flow_rate=45.0,
            rainfall=55.0,
            drainage_capacity=64.0,
            risk_level="MODERATE",
            confidence=96.0,
            sensor_status="ONLINE",
            data_source="DEMO/SIMULATED",
            battery_level=98.0,
            trend="steady",
            last_updated=now - timedelta(minutes=9)
        ),
        models.MonitoringStation(
            id="STN-TN-CHE-014",
            name="Red Hills Reservoir Inflow Weir",
            station_type="reservoir_spillway",
            country_id="india",
            state_id="tamil_nadu",
            district_id="dist-tiruvallur",
            city_id="chennai",
            latitude=13.1980,
            longitude=80.1870,
            water_level=3.20,
            warning_level=3.80,
            danger_level=4.80,
            flow_rate=320.0,
            rainfall=48.0,
            drainage_capacity=75.0,
            risk_level="LOW",
            confidence=99.0,
            sensor_status="ONLINE",
            data_source="DEMO/SIMULATED",
            battery_level=100.0,
            trend="steady",
            last_updated=now - timedelta(minutes=12)
        ),
        models.MonitoringStation(
            id="STN-TN-CHE-015",
            name="Avadi Paruthipattu Lake Outlet",
            station_type="urban_storm_drain",
            country_id="india",
            state_id="tamil_nadu",
            district_id="dist-tiruvallur",
            city_id="chennai",
            latitude=13.1147,
            longitude=80.1012,
            water_level=1.30,
            warning_level=1.40,
            danger_level=1.80,
            flow_rate=38.0,
            rainfall=50.0,
            drainage_capacity=68.0,
            risk_level="MODERATE",
            confidence=95.0,
            sensor_status="ONLINE",
            data_source="DEMO/SIMULATED",
            battery_level=96.0,
            trend="steady",
            last_updated=now - timedelta(minutes=10)
        ),
        models.MonitoringStation(
            id="STN-TN-CHE-016",
            name="Ennore Creek Tidal Flume",
            station_type="coastal_tide_station",
            country_id="india",
            state_id="tamil_nadu",
            district_id="dist-tiruvallur",
            city_id="chennai",
            latitude=13.2200,
            longitude=80.3200,
            water_level=1.80,
            warning_level=2.00,
            danger_level=2.50,
            flow_rate=210.0,
            rainfall=52.0,
            drainage_capacity=70.0,
            risk_level="LOW",
            confidence=97.0,
            sensor_status="ONLINE",
            data_source="DEMO/SIMULATED",
            battery_level=94.0,
            trend="steady",
            last_updated=now - timedelta(minutes=15)
        ),
        models.MonitoringStation(
            id="STN-TN-CHE-017",
            name="Vyasarpadi Railway Underpass Sump",
            station_type="urban_storm_drain",
            country_id="india",
            state_id="tamil_nadu",
            district_id="dist-chennai",
            city_id="chennai",
            latitude=13.1090,
            longitude=80.2580,
            water_level=1.35,
            warning_level=0.90,
            danger_level=1.20,
            flow_rate=28.0,
            rainfall=65.0,
            drainage_capacity=42.0,
            risk_level="CRITICAL",
            confidence=95.0,
            sensor_status="ALERT",
            data_source="DEMO/SIMULATED",
            battery_level=89.0,
            trend="rising",
            last_updated=now - timedelta(minutes=3)
        ),
        models.MonitoringStation(
            id="STN-TN-CHE-018",
            name="Adyar Estuary Tidal Gauge",
            station_type="coastal_tide_station",
            country_id="india",
            state_id="tamil_nadu",
            district_id="dist-chennai",
            city_id="chennai",
            latitude=13.0110,
            longitude=80.2780,
            water_level=2.10,
            warning_level=2.20,
            danger_level=2.80,
            flow_rate=390.0,
            rainfall=60.0,
            drainage_capacity=62.0,
            risk_level="MODERATE",
            confidence=96.0,
            sensor_status="ONLINE",
            data_source="DEMO/SIMULATED",
            battery_level=97.0,
            trend="steady",
            last_updated=now - timedelta(minutes=7)
        ),
        models.MonitoringStation(
            id="STN-TN-CUD-019",
            name="Cuddalore Pennaiyar River Estuary",
            station_type="river_gauge",
            country_id="india",
            state_id="tamil_nadu",
            district_id="dist-cuddalore",
            city_id="chennai",
            latitude=11.7480,
            longitude=79.7714,
            water_level=3.40,
            warning_level=2.60,
            danger_level=3.20,
            flow_rate=580.0,
            rainfall=92.0,
            drainage_capacity=38.0,
            risk_level="CRITICAL",
            confidence=98.0,
            sensor_status="ALERT",
            data_source="DEMO/SIMULATED",
            battery_level=91.0,
            trend="rising",
            last_updated=now - timedelta(minutes=2)
        ),
        models.MonitoringStation(
            id="STN-TN-CUD-020",
            name="Chidambaram Coleroon Floodway",
            station_type="river_gauge",
            country_id="india",
            state_id="tamil_nadu",
            district_id="dist-cuddalore",
            city_id="chennai",
            latitude=11.3990,
            longitude=79.6930,
            water_level=2.90,
            warning_level=2.40,
            danger_level=3.00,
            flow_rate=460.0,
            rainfall=84.0,
            drainage_capacity=46.0,
            risk_level="HIGH",
            confidence=96.0,
            sensor_status="ALERT",
            data_source="DEMO/SIMULATED",
            battery_level=93.0,
            trend="rising",
            last_updated=now - timedelta(minutes=4)
        ),
        models.MonitoringStation(
            id="STN-TN-MAD-021",
            name="Madurai Vaigai River Causeway",
            station_type="river_gauge",
            country_id="india",
            state_id="tamil_nadu",
            district_id="dist-madurai",
            city_id="chennai",
            latitude=9.9252,
            longitude=78.1198,
            water_level=1.80,
            warning_level=2.00,
            danger_level=2.60,
            flow_rate=210.0,
            rainfall=38.0,
            drainage_capacity=72.0,
            risk_level="MODERATE",
            confidence=94.0,
            sensor_status="ONLINE",
            data_source="DEMO/SIMULATED",
            battery_level=98.0,
            trend="steady",
            last_updated=now - timedelta(minutes=11)
        ),
        models.MonitoringStation(
            id="STN-TN-CBE-022",
            name="Coimbatore Noyyal River Channelling",
            station_type="river_gauge",
            country_id="india",
            state_id="tamil_nadu",
            district_id="dist-coimbatore",
            city_id="chennai",
            latitude=11.0020,
            longitude=76.9620,
            water_level=0.95,
            warning_level=1.60,
            danger_level=2.20,
            flow_rate=64.0,
            rainfall=18.0,
            drainage_capacity=82.0,
            risk_level="LOW",
            confidence=95.0,
            sensor_status="ONLINE",
            data_source="DEMO/SIMULATED",
            battery_level=99.0,
            trend="falling",
            last_updated=now - timedelta(minutes=14)
        ),

        # =========================================================================
        # MAHARASHTRA - MUMBAI REGION (6 STATIONS)
        # =========================================================================
        models.MonitoringStation(
            id="STN-MH-MUM-001",
            name="Mithi River - BKC Bridge Telemetry",
            station_type="river_gauge",
            country_id="india",
            state_id="maharashtra",
            district_id="dist-mumbai-suburban",
            city_id="mumbai",
            latitude=19.0650,
            longitude=72.8680,
            water_level=3.65,
            warning_level=3.00,
            danger_level=3.80,
            flow_rate=480.0,
            rainfall=62.0,
            drainage_capacity=42.0,
            risk_level="CRITICAL",
            confidence=97.0,
            sensor_status="ALERT",
            data_source="DEMO/SIMULATED",
            battery_level=92.0,
            trend="rising",
            last_updated=now - timedelta(minutes=2)
        ),
        models.MonitoringStation(
            id="STN-MH-MUM-002",
            name="Hindmata Flyover Dewatering Sump",
            station_type="urban_storm_drain",
            country_id="india",
            state_id="maharashtra",
            district_id="dist-mumbai-urban",
            city_id="mumbai",
            latitude=19.0110,
            longitude=72.8420,
            water_level=1.15,
            warning_level=0.80,
            danger_level=1.00,
            flow_rate=32.0,
            rainfall=58.0,
            drainage_capacity=36.0,
            risk_level="CRITICAL",
            confidence=95.0,
            sensor_status="ALERT",
            data_source="DEMO/SIMULATED",
            battery_level=90.0,
            trend="rising",
            last_updated=now - timedelta(minutes=3)
        ),
        models.MonitoringStation(
            id="STN-MH-MUM-003",
            name="Milan Subway Automated Sensor",
            station_type="urban_storm_drain",
            country_id="india",
            state_id="maharashtra",
            district_id="dist-mumbai-suburban",
            city_id="mumbai",
            latitude=19.0900,
            longitude=72.8450,
            water_level=0.95,
            warning_level=0.60,
            danger_level=0.80,
            flow_rate=18.0,
            rainfall=54.0,
            drainage_capacity=44.0,
            risk_level="HIGH",
            confidence=94.0,
            sensor_status="ALERT",
            data_source="DEMO/SIMULATED",
            battery_level=94.0,
            trend="rising",
            last_updated=now - timedelta(minutes=4)
        ),
        models.MonitoringStation(
            id="STN-MH-MUM-004",
            name="Powai Lake Surplus Spillway",
            station_type="reservoir_spillway",
            country_id="india",
            state_id="maharashtra",
            district_id="dist-mumbai-suburban",
            city_id="mumbai",
            latitude=19.1260,
            longitude=72.9050,
            water_level=2.10,
            warning_level=2.00,
            danger_level=2.50,
            flow_rate=95.0,
            rainfall=46.0,
            drainage_capacity=68.0,
            risk_level="MODERATE",
            confidence=96.0,
            sensor_status="ONLINE",
            data_source="DEMO/SIMULATED",
            battery_level=97.0,
            trend="steady",
            last_updated=now - timedelta(minutes=6)
        ),
        models.MonitoringStation(
            id="STN-MH-THA-005",
            name="Thane Creek Tidal Sluice Station",
            station_type="coastal_tide_station",
            country_id="india",
            state_id="maharashtra",
            district_id="dist-thane",
            city_id="mumbai",
            latitude=19.1850,
            longitude=72.9820,
            water_level=2.30,
            warning_level=2.50,
            danger_level=3.00,
            flow_rate=180.0,
            rainfall=42.0,
            drainage_capacity=72.0,
            risk_level="MODERATE",
            confidence=95.0,
            sensor_status="ONLINE",
            data_source="DEMO/SIMULATED",
            battery_level=98.0,
            trend="steady",
            last_updated=now - timedelta(minutes=8)
        ),
        models.MonitoringStation(
            id="STN-MH-PUN-006",
            name="Mutha River - Deccan Causeway",
            station_type="river_gauge",
            country_id="india",
            state_id="maharashtra",
            district_id="dist-pune",
            city_id="mumbai",
            latitude=18.5180,
            longitude=73.8420,
            water_level=1.20,
            warning_level=1.80,
            danger_level=2.40,
            flow_rate=110.0,
            rainfall=22.0,
            drainage_capacity=85.0,
            risk_level="LOW",
            confidence=96.0,
            sensor_status="ONLINE",
            data_source="DEMO/SIMULATED",
            battery_level=99.0,
            trend="steady",
            last_updated=now - timedelta(minutes=14)
        ),

        # =========================================================================
        # KARNATAKA - BENGALURU & COASTAL (5 STATIONS)
        # =========================================================================
        models.MonitoringStation(
            id="STN-KA-BLR-001",
            name="Bellandur Lake Surplus Spillway",
            station_type="reservoir_spillway",
            country_id="india",
            state_id="karnataka",
            district_id="dist-bengaluru-urban",
            city_id="bengaluru",
            latitude=12.9350,
            longitude=77.6780,
            water_level=2.40,
            warning_level=2.10,
            danger_level=2.60,
            flow_rate=140.0,
            rainfall=38.0,
            drainage_capacity=45.0,
            risk_level="HIGH",
            confidence=96.0,
            sensor_status="ALERT",
            data_source="DEMO/SIMULATED",
            battery_level=95.0,
            trend="rising",
            last_updated=now - timedelta(minutes=3)
        ),
        models.MonitoringStation(
            id="STN-KA-BLR-002",
            name="Varthur Lake Outlet Channel",
            station_type="urban_storm_drain",
            country_id="india",
            state_id="karnataka",
            district_id="dist-bengaluru-urban",
            city_id="bengaluru",
            latitude=12.9520,
            longitude=77.7420,
            water_level=2.15,
            warning_level=2.00,
            danger_level=2.50,
            flow_rate=115.0,
            rainfall=35.0,
            drainage_capacity=52.0,
            risk_level="MODERATE",
            confidence=94.0,
            sensor_status="ONLINE",
            data_source="DEMO/SIMULATED",
            battery_level=97.0,
            trend="steady",
            last_updated=now - timedelta(minutes=5)
        ),
        models.MonitoringStation(
            id="STN-KA-BLR-003",
            name="Outer Ring Road - Ecospace Culvert",
            station_type="culvert_sensor",
            country_id="india",
            state_id="karnataka",
            district_id="dist-bengaluru-urban",
            city_id="bengaluru",
            latitude=12.9230,
            longitude=77.6850,
            water_level=0.85,
            warning_level=0.55,
            danger_level=0.75,
            flow_rate=26.0,
            rainfall=42.0,
            drainage_capacity=38.0,
            risk_level="CRITICAL",
            confidence=97.0,
            sensor_status="ALERT",
            data_source="DEMO/SIMULATED",
            battery_level=93.0,
            trend="rising",
            last_updated=now - timedelta(minutes=2)
        ),
        models.MonitoringStation(
            id="STN-KA-BLR-004",
            name="Hebbal Stormwater Major Nala",
            station_type="urban_storm_drain",
            country_id="india",
            state_id="karnataka",
            district_id="dist-bengaluru-urban",
            city_id="bengaluru",
            latitude=13.0380,
            longitude=77.5920,
            water_level=1.10,
            warning_level=1.40,
            danger_level=1.80,
            flow_rate=45.0,
            rainfall=24.0,
            drainage_capacity=75.0,
            risk_level="LOW",
            confidence=95.0,
            sensor_status="ONLINE",
            data_source="DEMO/SIMULATED",
            battery_level=98.0,
            trend="falling",
            last_updated=now - timedelta(minutes=10)
        ),
        models.MonitoringStation(
            id="STN-KA-MNG-005",
            name="Netravati River - Mangaluru Bridge",
            station_type="river_gauge",
            country_id="india",
            state_id="karnataka",
            district_id="dist-dakshina-kannada",
            city_id="bengaluru",
            latitude=12.8450,
            longitude=74.8580,
            water_level=3.20,
            warning_level=3.00,
            danger_level=4.20,
            flow_rate=380.0,
            rainfall=64.0,
            drainage_capacity=65.0,
            risk_level="MODERATE",
            confidence=96.0,
            sensor_status="ONLINE",
            data_source="DEMO/SIMULATED",
            battery_level=96.0,
            trend="steady",
            last_updated=now - timedelta(minutes=7)
        ),

        # =========================================================================
        # KERALA - KOCHI & WAYANAD (4 STATIONS)
        # =========================================================================
        models.MonitoringStation(
            id="STN-KL-EKM-001",
            name="Periyar River - Aluva Manappuram Gauge",
            station_type="river_gauge",
            country_id="india",
            state_id="kerala",
            district_id="dist-ernakulam",
            city_id="chennai",
            latitude=10.1110,
            longitude=76.3530,
            water_level=4.10,
            warning_level=3.20,
            danger_level=4.00,
            flow_rate=720.0,
            rainfall=96.0,
            drainage_capacity=40.0,
            risk_level="CRITICAL",
            confidence=98.0,
            sensor_status="ALERT",
            data_source="DEMO/SIMULATED",
            battery_level=92.0,
            trend="rising",
            last_updated=now - timedelta(minutes=1)
        ),
        models.MonitoringStation(
            id="STN-KL-EKM-002",
            name="Vembanad Lake Estuary Spillway",
            station_type="coastal_tide_station",
            country_id="india",
            state_id="kerala",
            district_id="dist-ernakulam",
            city_id="chennai",
            latitude=9.9450,
            longitude=76.2800,
            water_level=2.65,
            warning_level=2.20,
            danger_level=2.80,
            flow_rate=410.0,
            rainfall=88.0,
            drainage_capacity=52.0,
            risk_level="HIGH",
            confidence=97.0,
            sensor_status="ALERT",
            data_source="DEMO/SIMULATED",
            battery_level=94.0,
            trend="rising",
            last_updated=now - timedelta(minutes=4)
        ),
        models.MonitoringStation(
            id="STN-KL-EKM-003",
            name="Kochi Marine Drive Stormwater Outfall",
            station_type="urban_storm_drain",
            country_id="india",
            state_id="kerala",
            district_id="dist-ernakulam",
            city_id="chennai",
            latitude=9.9780,
            longitude=76.2750,
            water_level=1.40,
            warning_level=1.30,
            danger_level=1.80,
            flow_rate=85.0,
            rainfall=82.0,
            drainage_capacity=60.0,
            risk_level="MODERATE",
            confidence=95.0,
            sensor_status="ONLINE",
            data_source="DEMO/SIMULATED",
            battery_level=97.0,
            trend="steady",
            last_updated=now - timedelta(minutes=6)
        ),
        models.MonitoringStation(
            id="STN-KL-WYD-004",
            name="Kabini River - Mananthavady Tributary",
            station_type="river_gauge",
            country_id="india",
            state_id="kerala",
            district_id="dist-wayanad",
            city_id="chennai",
            latitude=11.8020,
            longitude=76.0040,
            water_level=3.40,
            warning_level=2.80,
            danger_level=3.50,
            flow_rate=360.0,
            rainfall=86.0,
            drainage_capacity=48.0,
            risk_level="HIGH",
            confidence=96.0,
            sensor_status="ALERT",
            data_source="DEMO/SIMULATED",
            battery_level=91.0,
            trend="rising",
            last_updated=now - timedelta(minutes=3)
        ),

        # =========================================================================
        # ASSAM - GUWAHATI & BRAHMAPUTRA (4 STATIONS)
        # =========================================================================
        models.MonitoringStation(
            id="STN-AS-GHY-001",
            name="Brahmaputra River - Saraighat Bridge",
            station_type="river_gauge",
            country_id="india",
            state_id="assam",
            district_id="dist-kamrup-metro",
            city_id="guwahati",
            latitude=26.1280,
            longitude=91.6820,
            water_level=51.40,
            warning_level=49.50,
            danger_level=50.80,
            flow_rate=18500.0,
            rainfall=78.0,
            drainage_capacity=35.0,
            risk_level="CRITICAL",
            confidence=99.0,
            sensor_status="ALERT",
            data_source="DEMO/SIMULATED",
            battery_level=96.0,
            trend="rising",
            last_updated=now - timedelta(minutes=1)
        ),
        models.MonitoringStation(
            id="STN-AS-GHY-002",
            name="Bharalu River Sluice Gate",
            station_type="urban_storm_drain",
            country_id="india",
            state_id="assam",
            district_id="dist-kamrup-metro",
            city_id="guwahati",
            latitude=26.1750,
            longitude=91.7380,
            water_level=3.80,
            warning_level=2.80,
            danger_level=3.50,
            flow_rate=145.0,
            rainfall=72.0,
            drainage_capacity=32.0,
            risk_level="CRITICAL",
            confidence=97.0,
            sensor_status="ALERT",
            data_source="DEMO/SIMULATED",
            battery_level=93.0,
            trend="rising",
            last_updated=now - timedelta(minutes=2)
        ),
        models.MonitoringStation(
            id="STN-AS-GHY-003",
            name="Deepor Beel Ramsar Inflow Regulator",
            station_type="reservoir_spillway",
            country_id="india",
            state_id="assam",
            district_id="dist-kamrup-metro",
            city_id="guwahati",
            latitude=26.1250,
            longitude=91.6550,
            water_level=2.40,
            warning_level=2.20,
            danger_level=2.80,
            flow_rate=95.0,
            rainfall=64.0,
            drainage_capacity=55.0,
            risk_level="HIGH",
            confidence=95.0,
            sensor_status="ALERT",
            data_source="DEMO/SIMULATED",
            battery_level=98.0,
            trend="rising",
            last_updated=now - timedelta(minutes=4)
        ),
        models.MonitoringStation(
            id="STN-AS-GHY-004",
            name="Rukminigaon - Dispur Underpass Drainage",
            station_type="urban_storm_drain",
            country_id="india",
            state_id="assam",
            district_id="dist-kamrup-metro",
            city_id="guwahati",
            latitude=26.1380,
            longitude=91.7920,
            water_level=1.15,
            warning_level=0.75,
            danger_level=1.00,
            flow_rate=22.0,
            rainfall=68.0,
            drainage_capacity=45.0,
            risk_level="HIGH",
            confidence=94.0,
            sensor_status="ALERT",
            data_source="DEMO/SIMULATED",
            battery_level=95.0,
            trend="steady",
            last_updated=now - timedelta(minutes=5)
        ),

        # =========================================================================
        # TELANGANA - HYDERABAD (3 STATIONS)
        # =========================================================================
        models.MonitoringStation(
            id="STN-TG-HYD-001",
            name="Musi River - Moosarambagh Causeway",
            station_type="river_gauge",
            country_id="india",
            state_id="telangana",
            district_id="dist-hyderabad",
            city_id="hyderabad",
            latitude=17.3760,
            longitude=78.5080,
            water_level=2.80,
            warning_level=2.20,
            danger_level=2.70,
            flow_rate=320.0,
            rainfall=38.0,
            drainage_capacity=48.0,
            risk_level="CRITICAL",
            confidence=97.0,
            sensor_status="ALERT",
            data_source="DEMO/SIMULATED",
            battery_level=94.0,
            trend="rising",
            last_updated=now - timedelta(minutes=2)
        ),
        models.MonitoringStation(
            id="STN-TG-HYD-002",
            name="Hussain Sagar Surplus Channel Weir",
            station_type="reservoir_spillway",
            country_id="india",
            state_id="telangana",
            district_id="dist-hyderabad",
            city_id="hyderabad",
            latitude=17.4240,
            longitude=78.4740,
            water_level=1.90,
            warning_level=1.70,
            danger_level=2.20,
            flow_rate=110.0,
            rainfall=32.0,
            drainage_capacity=68.0,
            risk_level="MODERATE",
            confidence=96.0,
            sensor_status="ONLINE",
            data_source="DEMO/SIMULATED",
            battery_level=98.0,
            trend="steady",
            last_updated=now - timedelta(minutes=6)
        ),
        models.MonitoringStation(
            id="STN-TG-HYD-003",
            name="Begumpet Nala Automated Telemetry",
            station_type="urban_storm_drain",
            country_id="india",
            state_id="telangana",
            district_id="dist-hyderabad",
            city_id="hyderabad",
            latitude=17.4420,
            longitude=78.4680,
            water_level=1.30,
            warning_level=1.20,
            danger_level=1.50,
            flow_rate=42.0,
            rainfall=34.0,
            drainage_capacity=62.0,
            risk_level="MODERATE",
            confidence=95.0,
            sensor_status="ONLINE",
            data_source="DEMO/SIMULATED",
            battery_level=96.0,
            trend="steady",
            last_updated=now - timedelta(minutes=9)
        ),

        # =========================================================================
        # WEST BENGAL & ODISHA & GUJARAT (5 STATIONS)
        # =========================================================================
        models.MonitoringStation(
            id="STN-WB-KOL-001",
            name="Hooghly River - Howrah Lock Gate",
            station_type="coastal_tide_station",
            country_id="india",
            state_id="west_bengal",
            district_id="dist-chennai",
            city_id="chennai",
            latitude=22.5850,
            longitude=88.3420,
            water_level=3.10,
            warning_level=2.80,
            danger_level=3.50,
            flow_rate=840.0,
            rainfall=42.0,
            drainage_capacity=60.0,
            risk_level="MODERATE",
            confidence=96.0,
            sensor_status="ONLINE",
            data_source="DEMO/SIMULATED",
            battery_level=97.0,
            trend="steady",
            last_updated=now - timedelta(minutes=8)
        ),
        models.MonitoringStation(
            id="STN-OD-CTC-001",
            name="Mahanadi River - Jobra Barrage",
            station_type="river_gauge",
            country_id="india",
            state_id="odisha",
            district_id="dist-chennai",
            city_id="chennai",
            latitude=20.4850,
            longitude=85.8980,
            water_level=4.80,
            warning_level=4.50,
            danger_level=5.50,
            flow_rate=1450.0,
            rainfall=52.0,
            drainage_capacity=68.0,
            risk_level="MODERATE",
            confidence=97.0,
            sensor_status="ONLINE",
            data_source="DEMO/SIMULATED",
            battery_level=98.0,
            trend="rising",
            last_updated=now - timedelta(minutes=5)
        ),
        models.MonitoringStation(
            id="STN-GJ-SUR-001",
            name="Tapi River - Singanpore Causeway",
            station_type="river_gauge",
            country_id="india",
            state_id="gujarat",
            district_id="dist-chennai",
            city_id="chennai",
            latitude=21.2250,
            longitude=72.8250,
            water_level=2.10,
            warning_level=2.80,
            danger_level=3.50,
            flow_rate=420.0,
            rainfall=15.0,
            drainage_capacity=85.0,
            risk_level="LOW",
            confidence=98.0,
            sensor_status="ONLINE",
            data_source="DEMO/SIMULATED",
            battery_level=100.0,
            trend="steady",
            last_updated=now - timedelta(minutes=18)
        )
    ]
    db.add_all(stations)
    db.commit()


def seed_all_data(db: Session):
    """Populates realistic multi-city baseline data and geographic monitoring grid."""
    # Ensure hierarchy and stations exist
    if not db.query(models.Country).first():
        seed_geographic_hierarchy(db)

    if not db.query(models.MonitoringStation).first():
        seed_monitoring_stations(db)

    if db.query(models.City).first():
        return  # Existing baseline models already seeded


    # 1. CITIES
    cities = [
        models.City(
            id="chennai",
            name="Chennai Metropolitan Area",
            state="Tamil Nadu",
            lat=13.0827,
            lng=80.2707,
            zoom=12,
            primary_drivers_json=json.dumps(["Monsoon Cloudburst", "Coastal High Tide Lock", "Lakes & Basin Overflow"]),
            rainfall_mm_hr=72.4,
            tide_height_m=3.85,
            river_level_m=3.42,
            drainage_efficiency=62.0,
            population_at_risk=428000,
            active_risk_level="critical",
            description="Coastal delta basin vulnerable to Northeast monsoon storm surges, flat topography, and lake overflow cascading through Adyar and Cooum river corridors."
        ),
        models.City(
            id="mumbai",
            name="Mumbai Greater Region",
            state="Maharashtra",
            lat=19.0760,
            lng=72.8777,
            zoom=12,
            primary_drivers_json=json.dumps(["Extreme Rainfall", "High Astronomical Tide", "Mithi River Swelling"]),
            rainfall_mm_hr=44.0,
            tide_height_m=4.2,
            river_level_m=2.9,
            drainage_efficiency=70.0,
            population_at_risk=310000,
            active_risk_level="high",
            description="Dense coastal peninsula where heavy southwest monsoon rains coincide with 4.5m Arabian Sea spring tides, submerging low-lying railway underpasses."
        ),
        models.City(
            id="bengaluru",
            name="Bengaluru Urban",
            state="Karnataka",
            lat=12.9716,
            lng=77.5946,
            zoom=12,
            primary_drivers_json=json.dumps(["Localized Cloudbursts", "Stormwater Encroachment", "Cascading Lake Breaches"]),
            rainfall_mm_hr=18.5,
            tide_height_m=0.0,
            river_level_m=1.2,
            drainage_efficiency=78.0,
            population_at_risk=145000,
            active_risk_level="moderate",
            description="Highland plateau with valley topography where rapid urban impervious expansion causes flash runoff into Bellandur-Varthur lake series."
        ),
        models.City(
            id="hyderabad",
            name="Hyderabad Metropolitan",
            state="Telangana",
            lat=17.3850,
            lng=78.4867,
            zoom=12,
            primary_drivers_json=json.dumps(["Intense Convective Storms", "Musi River Inundation", "Nala Surcharge"]),
            rainfall_mm_hr=12.0,
            tide_height_m=0.0,
            river_level_m=1.8,
            drainage_efficiency=82.0,
            population_at_risk=95000,
            active_risk_level="low",
            description="Deccan plateau basin drained by the Musi River, where intense short-duration rain causes sudden swelling of natural nalas and old city pockets."
        ),
        models.City(
            id="guwahati",
            name="Guwahati & Kamrup Metro",
            state="Assam",
            lat=26.1445,
            lng=91.7362,
            zoom=12,
            primary_drivers_json=json.dumps(["Brahmaputra Backflow", "Hill Runoff Siltation", "Wetland Shrinkage"]),
            rainfall_mm_hr=32.0,
            tide_height_m=0.0,
            river_level_m=4.8,
            drainage_efficiency=64.0,
            population_at_risk=185000,
            active_risk_level="high",
            description="Riverine corridor nestled between Meghalaya hills and the mighty Brahmaputra river, prone to simultaneous flash hillside runoff and river backflow."
        )
    ]
    db.add_all(cities)

    # 2. FLOOD ZONES
    flood_zones = [
        models.FloodZone(
            id="fz-1",
            city_id="chennai",
            name="Velachery Lake Basin (Ward 177)",
            risk_level="critical",
            water_depth_m=0.95,
            predicted_depth_m=1.20,
            flood_arrival_minutes=15,
            affected_population=68400,
            coord_lat=12.9790,
            coord_lng=80.2185,
            area_km2=4.2,
            drain_status="overflowing",
            status_description="Velachery lake surplus channel overwhelmed. Inundation reaching 1m on arterial crossings."
        ),
        models.FloodZone(
            id="fz-2",
            city_id="chennai",
            name="Madipakkam South Lowland",
            risk_level="high",
            water_depth_m=0.68,
            predicted_depth_m=0.85,
            flood_arrival_minutes=35,
            affected_population=42000,
            coord_lat=12.9620,
            coord_lng=80.1980,
            area_km2=3.8,
            drain_status="partially_blocked",
            status_description="Stormwater lines backlogged due to slow culvert discharge into Pallikaranai marshland."
        ),
        models.FloodZone(
            id="fz-3",
            city_id="chennai",
            name="Mudichur - Varadarajapuram",
            risk_level="critical",
            water_depth_m=1.10,
            predicted_depth_m=1.35,
            flood_arrival_minutes=20,
            affected_population=51000,
            coord_lat=12.9210,
            coord_lng=80.0680,
            area_km2=5.6,
            drain_status="overflowing",
            status_description="Adyar river tributary overflow. Ground floor apartments submerged; boat evacuation active."
        ),
        models.FloodZone(
            id="fz-4",
            city_id="chennai",
            name="Saidapet Causeway Buffer",
            risk_level="high",
            water_depth_m=0.55,
            predicted_depth_m=0.80,
            flood_arrival_minutes=45,
            affected_population=38500,
            coord_lat=13.0180,
            coord_lng=80.2240,
            area_km2=2.1,
            drain_status="partially_blocked",
            status_description="River stage 3.4m. Low causeway closed to non-emergency vehicular traffic."
        ),
        models.FloodZone(
            id="fz-5",
            city_id="mumbai",
            name="Kurla - Mithi River Bank",
            risk_level="high",
            water_depth_m=0.72,
            predicted_depth_m=0.95,
            flood_arrival_minutes=30,
            affected_population=84000,
            coord_lat=19.0650,
            coord_lng=72.8800,
            area_km2=4.5,
            drain_status="overflowing",
            status_description="Mithi river reaching bankfull level coincident with high tide lock."
        ),
        models.FloodZone(
            id="fz-6",
            city_id="bengaluru",
            name="Rainbow Drive - Sarjapur Road Basin",
            risk_level="moderate",
            water_depth_m=0.45,
            predicted_depth_m=0.60,
            flood_arrival_minutes=60,
            affected_population=18500,
            coord_lat=12.9150,
            coord_lng=77.6850,
            area_km2=2.4,
            drain_status="partially_blocked",
            status_description="Inflow culvert choked with debris; tractors operating for localized transit."
        )
    ]
    db.add_all(flood_zones)

    # 3. ROAD SEGMENTS
    roads = [
        models.RoadSegment(
            id="rd-1",
            city_id="chennai",
            name="Velachery Main Road (Vijayanagar Junct.)",
            status="closed",
            water_depth_m=0.85,
            predicted_depth_m=1.05,
            max_passable_clearance_m=0.30,
            eta_to_inundation_min=0,
            is_alternate_route=False,
            start_lat=12.9810,
            start_lng=80.2180,
            end_lat=12.9750,
            end_lng=80.2220,
            verified_by_ground=True,
            last_reported_by="Traffic Police Inspector R. Murugan"
        ),
        models.RoadSegment(
            id="rd-2",
            city_id="chennai",
            name="Rajiv Gandhi Salai (OMR Elevated Corridor)",
            status="passable",
            water_depth_m=0.08,
            predicted_depth_m=0.12,
            max_passable_clearance_m=0.60,
            eta_to_inundation_min=180,
            is_alternate_route=True,
            start_lat=12.9900,
            start_lng=80.2450,
            end_lat=12.9400,
            end_lng=80.2380,
            verified_by_ground=True,
            last_reported_by="Hydrological Telemetry Radar"
        ),
        models.RoadSegment(
            id="rd-3",
            city_id="chennai",
            name="GST Road (Near Airport Subways)",
            status="risky",
            water_depth_m=0.38,
            predicted_depth_m=0.52,
            max_passable_clearance_m=0.45,
            eta_to_inundation_min=25,
            is_alternate_route=False,
            start_lat=12.9850,
            start_lng=80.1650,
            end_lat=12.9550,
            end_lng=80.1420,
            verified_by_ground=False,
            last_reported_by="Dewatering Field Sensor #GST-08"
        ),
        models.RoadSegment(
            id="rd-4",
            city_id="chennai",
            name="Mount-Poonamallee High Road",
            status="passable",
            water_depth_m=0.15,
            predicted_depth_m=0.22,
            max_passable_clearance_m=0.40,
            eta_to_inundation_min=90,
            is_alternate_route=True,
            start_lat=13.0200,
            start_lng=80.1800,
            end_lat=13.0350,
            end_lng=80.1500,
            verified_by_ground=True,
            last_reported_by="PWD Road Patrol"
        )
    ]
    db.add_all(roads)

    # 4. HOSPITALS
    hospitals = [
        models.Hospital(
            id="hosp-1",
            city_id="chennai",
            name="Gleneagles Global Health City",
            coord_lat=12.9020,
            coord_lng=80.2110,
            total_beds=450,
            available_beds=94,
            icu_beds_total=60,
            icu_beds_available=14,
            ambulances_available=6,
            power_status="grid_online",
            oxygen_supply_hours=96.0,
            water_accessible=True,
            incoming_emergencies=8
        ),
        models.Hospital(
            id="hosp-2",
            city_id="chennai",
            name="Dr. Kamakshi Memorial Hospital",
            coord_lat=12.9580,
            coord_lng=80.2050,
            total_beds=300,
            available_beds=18,
            icu_beds_total=40,
            icu_beds_available=3,
            ambulances_available=2,
            power_status="generator_backup",
            oxygen_supply_hours=36.0,
            water_accessible=False,
            incoming_emergencies=16
        ),
        models.Hospital(
            id="hosp-3",
            city_id="chennai",
            name="Government Multi Super Speciality Hospital (Omandurar)",
            coord_lat=13.0690,
            coord_lng=80.2760,
            total_beds=500,
            available_beds=140,
            icu_beds_total=80,
            icu_beds_available=28,
            ambulances_available=11,
            power_status="grid_online",
            oxygen_supply_hours=120.0,
            water_accessible=True,
            incoming_emergencies=5
        )
    ]
    db.add_all(hospitals)

    # 5. SHELTERS
    shelters = [
        models.Shelter(
            id="sh-1",
            city_id="chennai",
            name="Velachery Community Relief Center (Ward 177)",
            coord_lat=12.9770,
            coord_lng=80.2220,
            capacity=650,
            occupancy=490,
            food_days_remaining=3.5,
            water_liters_remaining=8400.0,
            medical_support_available=True,
            power_status="backup",
            accessibility_status="high_clearance_only",
            contact_person="R. Senthil Kumar (Tahsildar)",
            phone="+91 94440 22341"
        ),
        models.Shelter(
            id="sh-2",
            city_id="chennai",
            name="Adyar Government Girls High School Shelter",
            coord_lat=13.0070,
            coord_lng=80.2520,
            capacity=800,
            occupancy=320,
            food_days_remaining=5.0,
            water_liters_remaining=14000.0,
            medical_support_available=True,
            power_status="normal",
            accessibility_status="fully_accessible",
            contact_person="K. Priya (Revenue Inspector)",
            phone="+91 94441 55678"
        ),
        models.Shelter(
            id="sh-3",
            city_id="chennai",
            name="Tambaram Sanatorium Indoor Stadium",
            coord_lat=12.9340,
            coord_lng=80.1250,
            capacity=1200,
            occupancy=780,
            food_days_remaining=2.0,
            water_liters_remaining=6200.0,
            medical_support_available=True,
            power_status="backup",
            accessibility_status="high_clearance_only",
            contact_person="V. Natarajan (Zonal Officer)",
            phone="+91 98402 11990"
        )
    ]
    db.add_all(shelters)

    # 6. VOLUNTEERS
    volunteers = [
        models.Volunteer(
            id="vol-1",
            city_id="chennai",
            name="Arun Sundaram",
            phone="+91 98401 33456",
            skills_json=json.dumps(["Boat Operator", "Swimmer", "First Aid"]),
            is_available=True,
            current_location="Velachery Vijayanagar Hub",
            coord_lat=12.9810,
            coord_lng=80.2190,
            active_task_id="task-rescue-702",
            completed_tasks_count=14,
            badge_level="Gold"
        ),
        models.Volunteer(
            id="vol-2",
            city_id="chennai",
            name="Dr. Sneha Balan",
            phone="+91 98840 88219",
            skills_json=json.dumps(["Medical Doctor", "Triage", "Pediatric Care"]),
            is_available=True,
            current_location="Adyar Shelter #2",
            coord_lat=13.0070,
            coord_lng=80.2520,
            active_task_id=None,
            completed_tasks_count=9,
            badge_level="Silver"
        ),
        models.Volunteer(
            id="vol-3",
            city_id="chennai",
            name="M. Vijay Anand",
            phone="+91 97910 44521",
            skills_json=json.dumps(["High Clearance Driver", "Heavy Machinery", "Logistics"]),
            is_available=True,
            current_location="Guindy Central Supply Depot",
            coord_lat=13.0110,
            coord_lng=80.2080,
            active_task_id=None,
            completed_tasks_count=19,
            badge_level="Gold"
        )
    ]
    db.add_all(volunteers)

    # 7. RELIEF RESOURCES
    resources = [
        models.ReliefResource(
            id="res-1",
            city_id="chennai",
            name="Ready-to-Eat Food Packets (Ration Packs)",
            category="food",
            quantity=8500,
            unit="packets",
            location_name="Guindy Central Supply Depot",
            allocated_to="Velachery Relief Center",
            status="in_transit"
        ),
        models.ReliefResource(
            id="res-2",
            city_id="chennai",
            name="Purified Potable Water Pouches (500ml)",
            category="water",
            quantity=35000,
            unit="pouches",
            location_name="Omandurar Central Stockpile",
            allocated_to=None,
            status="available"
        ),
        models.ReliefResource(
            id="res-3",
            city_id="chennai",
            name="Motorized Inflatable Zodiac Rescue Boats",
            category="boats",
            quantity=18,
            unit="crafts",
            location_name="Fire & Rescue Marine Command",
            allocated_to="Sector 4 Mudichur",
            status="allocated"
        ),
        models.ReliefResource(
            id="res-4",
            city_id="chennai",
            name="High-Density Polymer Geotextile Sandbags",
            category="sandbags",
            quantity=12000,
            unit="bags",
            location_name="PWD Adyar River Yard",
            allocated_to="Saidapet Bund",
            status="available"
        )
    ]
    db.add_all(resources)

    # 8. FLEET VEHICLES
    fleet = [
        models.FleetVehicle(
            id="flt-1",
            city_id="chennai",
            callsign="BOAT-ALPHA-01",
            type="rescue_boat",
            status="on_scene",
            current_location="Tansi Nagar 5th Street",
            coord_lat=12.9815,
            coord_lng=80.2180,
            assigned_mission="SOS #702 Evacuation of stranded infant & family",
            fuel_percentage=84.0,
            driver_name="Havildar Rajesh Kumar"
        ),
        models.FleetVehicle(
            id="flt-2",
            city_id="chennai",
            callsign="AMB-ALS-108",
            type="ambulance",
            status="en_route",
            current_location="OMR Elevated Link",
            coord_lat=12.9700,
            coord_lng=80.2410,
            assigned_mission="Emergency Neonatal Triage Transfer to Gleneagles",
            fuel_percentage=92.0,
            driver_name="Paramedic D. Stalin"
        ),
        models.FleetVehicle(
            id="flt-3",
            city_id="chennai",
            callsign="TRK-CLEAR-04",
            type="high_clearance_truck",
            status="idle",
            current_location="Guindy Central Supply Depot",
            coord_lat=13.0110,
            coord_lng=80.2080,
            assigned_mission=None,
            fuel_percentage=78.0,
            driver_name="Operator P. Ganesan"
        ),
        models.FleetVehicle(
            id="flt-4",
            city_id="chennai",
            callsign="PUMP-TRK-2000",
            type="dewatering_pump_truck",
            status="on_scene",
            current_location="Airport Subway Arterial Underpass",
            coord_lat=12.9850,
            coord_lng=80.1650,
            assigned_mission="High-pressure dewatering to keep airport transit clear",
            fuel_percentage=65.0,
            driver_name="Er. K. Suresh"
        )
    ]
    db.add_all(fleet)

    # 9. DAM RESERVOIR
    dam = models.DamReservoir(
        id="dam-1",
        city_id="chennai",
        name="Chembarambakkam Reservoir",
        current_level_m=22.45,
        full_reservoir_level_m=24.00,
        storage_percentage=84.8,
        inflow_cusecs=14200.0,
        outflow_cusecs=8000.0,
        gate_count=19,
        open_gates=6,
        planned_release_cusecs=9500.0,
        downstream_risk_level="warning",
        rainfall_catchment_mm=82.5,
        trend="rising",
        ai_recommendation="Catchment inflow rising sharply (+14.2k cusecs). Advise gradual gate ramp-up to 9,500 cusecs before dark to protect downstream bunds."
    )
    db.add(dam)

    # 10. AI AGENTS
    agents = [
        models.AIAgentState(
            id="agent_flood_intel",
            name="Flood Intelligence Agent",
            role="Nowcasting & Inundation Physics Modeling",
            status="active",
            current_task="Analyzing dual Doppler radar telemetry and 42 river basin telemetry gauges",
            recent_input="Cloudburst spike (88.0 mm/hr) detected over Velachery catchment corridor",
            decision="Raised Basin Inundation Probability to 96%; projected peak water level 1.15m at T+25m",
            confidence=96,
            last_updated="Just now",
            icon_name="CloudRain"
        ),
        models.AIAgentState(
            id="agent_incident_verify",
            name="Incident Verification Agent",
            role="Crowdsource Triage & Ground Truth Validation",
            status="active",
            current_task="Ingesting citizen SOS alerts and sensor data for automated cross-validation",
            recent_input="Received SOS #702 from Tansi Nagar reporting 0.85m water depth",
            decision="Cross-referenced with depth sensor #VEL-04 (0.88m). Incident tagged VERIFIED HIGH PRIORITY",
            confidence=98,
            last_updated="1 min ago",
            icon_name="CheckCircle"
        ),
        models.AIAgentState(
            id="agent_routing",
            name="Emergency Routing Agent",
            role="Dynamic Clear-Corridor Pathfinding",
            status="coordinating",
            current_task="Calculating multi-modal transit graph with road passability constraints",
            recent_input="Velachery Main Road blocked with 0.85m standing flood water",
            decision="Enforced detour via Rajiv Gandhi Salai (OMR Elevated Corridor). Saves 14 min transit time",
            confidence=94,
            last_updated="Just now",
            icon_name="Compass"
        ),
        models.AIAgentState(
            id="agent_resource",
            name="Resource Allocation Agent",
            role="Warehouse Logistics & Supply Matching",
            status="active",
            current_task="Balancing shelter consumables with depot inventory replenishment schedules",
            recent_input="Velachery Relief Center #1 approaching 80% shelter capacity",
            decision="Dispatched High-Clearance Truck #04 with 1,200 ration packets and 4,000 water pouches",
            confidence=95,
            last_updated="2 min ago",
            icon_name="PackageCheck"
        ),
        models.AIAgentState(
            id="agent_medical",
            name="Medical Coordination Agent",
            role="Hospital ICU & Patient Evacuation Routing",
            status="active",
            current_task="Tracking ICU bed capacity, generator diesel reserves, and oxygen levels",
            recent_input="Kamakshi Hospital access road inundated; backup generator active",
            decision="Rerouted 6 emergency ambulances to Gleneagles Global (14 ICU beds clear)",
            confidence=97,
            last_updated="Just now",
            icon_name="Stethoscope"
        ),
        models.AIAgentState(
            id="agent_volunteer",
            name="Volunteer Coordination Agent",
            role="Skill-Based Task Assignment & Buddy Pairing",
            status="monitoring",
            current_task="Scanning available volunteer roster against unresolved emergency beacons",
            recent_input="Gold-badge volunteer Arun Sundaram flagged available at Vijayanagar Hub",
            decision="Dispatched volunteer team for elderly escort in Tansi Nagar Sector 2",
            confidence=91,
            last_updated="3 min ago",
            icon_name="Users"
        ),
        models.AIAgentState(
            id="agent_dam",
            name="Dam Risk Agent",
            role="Reservoir Mass Balance & Release Wave Simulation",
            status="active",
            current_task="Running hydrodynamic routing model for Chembarambakkam discharge wave",
            recent_input="Inflow jumped to 14,200 cusecs; storage at 84.8% FRL",
            decision="Projected downstream Saidapet causeway crest at T+54 min. Early warning transmitted",
            confidence=96,
            last_updated="Just now",
            icon_name="Waves"
        ),
        models.AIAgentState(
            id="agent_commander",
            name="Commander Agent",
            role="Multi-Agent Synthesis & Executive Decisions",
            status="coordinating",
            current_task="Synthesizing multi-domain telemetry for District Collector authorization",
            recent_input="Unified emergency trigger reached across 3 sectors",
            decision="Synthesized Action Plan #702: Human-in-the-loop approval submitted to SEOC desk",
            confidence=99,
            last_updated="Just now",
            icon_name="ShieldAlert"
        )
    ]
    db.add_all(agents)

    # 11. IMPACT ALERTS
    alerts = [
        models.ImpactAlert(
            id="alt-1",
            city_id="chennai",
            title="CRITICAL FLASH FLOOD WARNING: VELACHERY & MADIPAKKAM",
            severity="extreme",
            location="Velachery Lake Basin, Madipakkam South",
            eta="Immediate (next 15-30 min)",
            recommended_action="Move to upper floors immediately. Avoid Velachery Main Road. Emergency shelter open at Ward 177 Community Hall.",
            target_audience="General public, emergency response fleet",
            active=True,
            issued_at="10 min ago"
        ),
        models.ImpactAlert(
            id="alt-2",
            city_id="chennai",
            title="CHEMBARAMBAKKAM DISCHARGE ADVISORY: ADYAR RIVERBANK",
            severity="severe",
            location="Saidapet, Kotturpuram, Jafferkhanpet Riverbank Buffer",
            eta="Arrival in ~50 minutes",
            recommended_action="Do not attempt to cross Maraimalai Adigal causeway. Evacuation teams operating with loudspeakers.",
            target_audience="Riverbank settlements and municipal squads",
            active=True,
            issued_at="25 min ago"
        )
    ]
    db.add_all(alerts)

    # 12. NOWCAST PREDICTIONS
    nowcasts = [
        models.NowcastPrediction(
            id="nc-1",
            city_id="chennai",
            road_name="Velachery Main Road (Vijayanagar)",
            flood_probability=96,
            predicted_depth_m=1.05,
            actual_depth_m=0.85,
            eta_minutes=15,
            duration_hours=4.5,
            confidence=96,
            verified_status="ground_verified_match",
            divergence_delta_m=0.03
        ),
        models.NowcastPrediction(
            id="nc-2",
            city_id="chennai",
            road_name="GST Road (Airport Subway Underpass)",
            flood_probability=78,
            predicted_depth_m=0.52,
            actual_depth_m=0.38,
            eta_minutes=25,
            duration_hours=3.0,
            confidence=89,
            verified_status="predicted",
            divergence_delta_m=0.06
        ),
        models.NowcastPrediction(
            id="nc-3",
            city_id="chennai",
            road_name="Rajiv Gandhi Salai (OMR Elevated)",
            flood_probability=12,
            predicted_depth_m=0.10,
            actual_depth_m=0.05,
            eta_minutes=180,
            duration_hours=1.0,
            confidence=97,
            verified_status="ground_verified_match",
            divergence_delta_m=0.01
        )
    ]
    db.add_all(nowcasts)

    # 13. SOS REQUESTS
    sos_requests = [
        models.SOSRequest(
            id="sos-702",
            city_id="chennai",
            citizen_name="Karthik Ramanathan",
            phone="+91 98403 99120",
            location_name="Flat 3B, Lake View Enclave, Tansi Nagar 5th Street",
            coord_lat=12.9815,
            coord_lng=80.2180,
            people_count=6,
            water_depth_m=0.85,
            has_medical_emergency=True,
            children_count=1,
            elderly_count=2,
            help_type="boat_evacuation",
            notes="Water has entered first floor staircase. 3-week-old infant and 78-year-old grandfather on oxygen concentrator.",
            status="responding",
            reported_at="12 min ago",
            assigned_vehicle_id="flt-1",
            assigned_volunteer_id="vol-1",
            priority_score=98.5
        ),
        models.SOSRequest(
            id="sos-703",
            city_id="chennai",
            citizen_name="Meenakshi Sundaram",
            phone="+91 97901 11244",
            location_name="Door 14, Bhuvaneshwari Nagar, Madipakkam",
            coord_lat=12.9630,
            coord_lng=80.1990,
            people_count=4,
            water_depth_m=0.60,
            has_medical_emergency=False,
            children_count=2,
            elderly_count=0,
            help_type="food_water",
            notes="No power since morning. Dry rations exhausted, drinking water required.",
            status="assigned",
            reported_at="24 min ago",
            assigned_vehicle_id="flt-3",
            assigned_volunteer_id="vol-3",
            priority_score=72.0
        )
    ]
    db.add_all(sos_requests)

    # 14. FIELD INCIDENTS
    incidents = [
        models.Incident(
            id="inc-101",
            city_id="chennai",
            title="Severe Waterlogging & Stalled Vehicles",
            location_name="Velachery Vijayanagar Junction",
            coord_lat=12.9810,
            coord_lng=80.2180,
            type="road_blockage",
            severity="critical",
            people_affected=120,
            water_depth_m=0.85,
            status="responding",
            reported_at="18 min ago",
            assigned_team="Traffic Police & Fire Unit 4",
            assigned_team_type="emergency_services",
            special_needs_json=json.dumps(["Traffic Diversion", "Wrecker Crane"]),
            description="3 metropolitan buses stalled; water level above vehicle exhausts."
        )
    ]
    db.add_all(incidents)

    # 15. ACTION APPROVAL REQUEST
    approval = models.ActionApprovalRequest(
        id="appr-1",
        agent_name="Commander Agent",
        title="Authorize Emergency Tactical Plan #702",
        description="Flash flood in Velachery Ward 177 requires immediate road closure and boat dispatch for SOS #702.",
        proposed_action="Close Velachery Main Road, divert traffic to OMR Elevated, and dispatch Zodiac Boat Alpha-01 with volunteer rescue team.",
        consequences="Closes arterial traffic for 3.5 hours; eliminates stranding hazard for 6 citizens including infant.",
        status="pending",
        created_at="5 min ago",
        severity="critical"
    )
    db.add(approval)

    # 16. INITIAL AGENT LOGS
    logs = [
        models.AgentActivityLog(
            id="log-init-1",
            agent_name="Commander Agent",
            action="System Initialization Complete",
            details="Hydrological digital twin synchronized for 5 major metropolitan regions.",
            timestamp="10:00:00",
            severity="info"
        ),
        models.AgentActivityLog(
            id="log-init-2",
            agent_name="Flood Intelligence Agent",
            action="Radar Nowcasting Triggered",
            details="Ingested radar precipitation volume (72.4 mm/hr) over Chennai metropolitan basin.",
            timestamp="10:02:15",
            severity="alert"
        ),
        models.AgentActivityLog(
            id="log-init-3",
            agent_name="Incident Verification Agent",
            action="SOS #702 Cross-Validation Passed",
            details="Ground depth telemetry matches citizen report with 97% spatial confidence.",
            timestamp="10:04:30",
            severity="success"
        )
    ]
    db.add_all(logs)

    db.commit()
